// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.lihaoyi" % "autowire_sjs0.6_2.11" % "0.2.6",
  "com.lihaoyi" % "scalatags_sjs0.6_2.11" % "0.6.5",
  "com.lihaoyi" % "sourcecode_sjs0.6_2.11" % "0.1.3",
  "io.suzaku" % "boopickle_sjs0.6_2.11" % "1.2.6",
  "org.scala-js" % "scalajs-dom_sjs0.6_2.11" % "0.9.2",
  "org.scala-js" % "scalajs-library_2.11" % "0.6.16"
)
// LIBRARY_DEPENDENCIES_HASH 129f741e2fc75cc35422cc72f1e418f09a704fbd
