var webpack = require('webpack');
var CompressionPlugin = require("compression-webpack-plugin");

// Load the config generated by scalajs-bundler
var config = require('./scalajs.webpack.config');

config.plugins = config.plugins || [];
config.plugins.push(new webpack.optimize.UglifyJsPlugin());
config.plugins.push(new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production')
}));
config.plugins.push(new CompressionPlugin({
  asset: "[path].gz[query]",
  algorithm: "gzip",
  test: /\.js$|\.html$/,
  minRatio: 0.0
}));

module.exports = config;
