FROM openjdk:8-jre-alpine

ENV SBT_VERSION 0.13.13
ENV SBT_HOME /usr/local/sbt-launcher-packaging-$SBT_VERSION
ENV PATH ${PATH}:${SBT_HOME}/bin

RUN apk add --no-cache bash

RUN wget -qO- "http://dl.bintray.com/sbt/native-packages/sbt/$SBT_VERSION/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /usr/local

RUN mkdir /src
WORKDIR /src

CMD dev
ENTRYPOINT sbt
