#!/usr/bin/env bash
set -e
set -o pipefail

git_branch=$(git symbolic-ref --short HEAD --quiet || git rev-parse HEAD) # branch, or fall back to commit hash

[[ "$git_branch" == "production" ]] || echo "Please switch to production branch to deploy production." && exit 0

OVERRIDE_BRANCH=production ci/build-docker

[[ -n "$DOCKER_USERNAME" ]] || exit 0
[[ -n "$DOCKER_PASSWORD" ]] || exit 0
[[ -n "$DOCKER_REGISTRY" ]] || exit 0

docker images | grep production
echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" "$DOCKER_REGISTRY" --password-stdin;

docker push "$DOCKER_REGISTRY/woost/db-migration:production-core"
docker push "$DOCKER_REGISTRY/woost/db-migration:production-slack"
docker push "$DOCKER_REGISTRY/woost/core:production"
docker push "$DOCKER_REGISTRY/woost/web:production"
# docker push "$DOCKER_REGISTRY/woost/github"
# docker push "$DOCKER_REGISTRY/woost/gitter"
docker push "$DOCKER_REGISTRY/woost/slack:production"

if [[ -n "$PRODUCTION_URL" ]]; then
    echo "Triggering production deploy..."
    sleep 3
    curl "$PRODUCTION_URL"
else
    echo "Not triggering deploy, since no PRODUCTION_URL given"
fi
