#!/usr/bin/env bash
set -e
set -o pipefail

git_branch=$(git symbolic-ref --short HEAD --quiet || git rev-parse HEAD) # branch, or fall back to commit hash

if [[ "$git_branch" != "staging" ]]; then
    echo "Please switch to staging branch to deploy staging."
    exit 0
fi

sbt clean
ci/build-docker

[[ -n "$DOCKER_USERNAME" ]] || exit 0
[[ -n "$DOCKER_PASSWORD" ]] || exit 0
[[ -n "$DOCKER_REGISTRY" ]] || exit 0

docker images | grep latest
echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" "$DOCKER_REGISTRY" --password-stdin;

docker tag "woost/db-migration:latest-core" "$DOCKER_REGISTRY/woost/db-migration:staging-core"
docker push "$DOCKER_REGISTRY/woost/db-migration:staging-core"
docker tag "woost/core:latest" "$DOCKER_REGISTRY/woost/core:staging"
docker push "$DOCKER_REGISTRY/woost/core:staging"
docker tag "woost/web:latest" "$DOCKER_REGISTRY/woost/web:staging"
docker push "$DOCKER_REGISTRY/woost/web:staging"

if [[ -n "$STAGING_URL" ]]; then
    echo "Triggering staging deploy..."
    sleep 3
    curl "$STAGING_URL"
else
    echo "Not triggering deploy, since no STAGING_URL given"
fi
