#!/bin/bash -e

export POSTGRES_DB=${POSTGRES_DB:-'wust'} \
       POSTGRES_USER=${POSTGRES_USER:-'test'} \
       POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-'test'}

stage="$1"
compose="$(dirname $0)/docker/compose $stage"

case $stage in
test.postgres)
    $compose down
    $compose up --build -d postgres
    $compose run test
    rc=$?
    $compose down
    exit $rc
    ;;
dev.docker)
    $compose down
    $compose build wust
    $compose run --service-ports wust sbt dev
    ;;
dev)
    $compose down
    $compose up --build -d
    POSTGRES_HOSTNAME=localhost sbt dev
    ;;
prod)
    sbt backend/assembly
    $compose down
    $compose up --build -d
    ;;
*)
    echo "unknown stage '$1', expected one of [dev,dev.docker,test.postgres,prod]"
    exit 1
esac
