// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(

)
// LIBRARY_DEPENDENCIES_HASH 73fb68ae6345d5653a73701882e4ccae0d15710b
