// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "io.suzaku" % "boopickle_2.11" % "1.2.6",
  "org.scala-lang.modules" % "scala-java8-compat_2.11" % "0.7.0",
  "org.scalaz" % "scalaz-core_2.11" % "7.3.0-M13"
)
// LIBRARY_DEPENDENCIES_HASH f6af33ebd11b6fc7f01d8e50621fef6b12fd402c
