#!/bin/bash -e

[[ "$TRAVIS_BRANCH" == "master" ]] || exit 0

sbt docker

docker images
# docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
# docker push woost/postgres
# docker push woost/wust2
