#!/bin/bash -e


sbt backend/assembly

[ "$TRAVIS_BRANCH" == "master" ] && TAG_POSTFIX="" || TAG_POSTFIX="-$TRAVIS_BRANCH"

latest="latest$TAG_POSTFIX"

docker build --tag "woost/postgres:$latest" postgres
docker build --build-arg version=0.1-SNAPSHOT --tag "woost/wust2:$latest" .

if [[ -n "${TRAVIS_TAG}" ]]; then
    version="$TRAVIS_TAG$TAG_POSTFIX"
    docker build --tag "woost/postgres:$version" postgres
    docker build --tag "woost/wust2:$version" .
fi

docker images
# docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
# docker push woost/postgres:latest
# docker push woost/wust2:latest
