// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.lihaoyi" % "autowire_2.11" % "0.2.6",
  "com.outr" % "scribe_2.11" % "1.4.2",
  "com.typesafe" % "config" % "1.3.1",
  "com.typesafe" % "ssl-config-core_2.11" % "0.2.1",
  "com.typesafe.akka" % "akka-actor_2.11" % "2.5.2",
  "com.typesafe.akka" % "akka-http-core_2.11" % "10.0.7",
  "com.typesafe.akka" % "akka-http_2.11" % "10.0.7",
  "com.typesafe.akka" % "akka-parsing_2.11" % "10.0.7",
  "com.typesafe.akka" % "akka-stream_2.11" % "2.4.18",
  "io.suzaku" % "boopickle_2.11" % "1.2.6",
  "org.reactivestreams" % "reactive-streams" % "1.0.0",
  "org.scala-lang.modules" % "scala-java8-compat_2.11" % "0.7.0",
  "org.scala-lang.modules" % "scala-parser-combinators_2.11" % "1.0.4"
)
// LIBRARY_DEPENDENCIES_HASH 71d1ae67506236672c46227f671fee20d9928f7b
