#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
    echo "usage: $(basename $0) stage <docker-compose args>"
    exit
fi

stage=$1
args="${@:2}"
base_compose_path="$(dirname $0)/compose.yml"
compose_path="$(dirname $0)/compose-$stage.yml"
compose_project="wust_$stage"

if [[ ! -e $compose_path ]]; then
    echo "stage $stage does not exist"
    exit 1
fi

docker-compose --project-name $compose_project --file $base_compose_path --file $compose_path $args
