// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.lihaoyi" % "scalatags_sjs0.6_2.11" % "0.6.5",
  "com.lihaoyi" % "sourcecode_sjs0.6_2.11" % "0.1.3",
  "org.scala-js" % "scalajs-dom_sjs0.6_2.11" % "0.9.1",
  "org.scala-js" % "scalajs-library_2.11" % "0.6.16"
)
// LIBRARY_DEPENDENCIES_HASH d386a4e49b39767437f28a3b3a25fb928385733a
