// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(

)
// LIBRARY_DEPENDENCIES_HASH 42a103c33394689ee31de1332d423b77e45f7270
