// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.github.mauricio" % "db-async-common_2.11" % "0.2.21",
  "com.github.mauricio" % "postgresql-async_2.11" % "0.2.21",
  "com.outr" % "scribe_2.11" % "1.4.2",
  "com.typesafe" % "config" % "1.3.1",
  "com.typesafe.scala-logging" % "scala-logging_2.11" % "3.5.0",
  "io.getquill" % "quill-async-postgres_2.11" % "1.2.1",
  "io.getquill" % "quill-async_2.11" % "1.2.1",
  "io.getquill" % "quill-core_2.11" % "1.2.1",
  "io.getquill" % "quill-sql_2.11" % "1.2.1",
  "io.netty" % "netty-all" % "4.1.6.Final",
  "joda-time" % "joda-time" % "2.9.7",
  "org.javassist" % "javassist" % "3.21.0-GA",
  "org.joda" % "joda-convert" % "1.8.1",
  "org.scala-lang.modules" % "scala-java8-compat_2.11" % "0.7.0",
  "org.scalamacros" % "resetallattrs_2.11" % "1.0.0",
  "org.scalaz" % "scalaz-core_2.11" % "7.3.0-M13",
  "org.slf4j" % "slf4j-api" % "1.7.22"
)
// LIBRARY_DEPENDENCIES_HASH 3f4ec8fd27e09c9be990f565f47692efb4dd02df
