#!/bin/bash
set -e
set -o pipefail

#TODO: remove when new monadic-html released (this is 0.2.4-SNAPSHOT)
git clone -b mario --single-branch --depth=1 https://github.com/OlivierBlanvillain/monadic-html
cd monadic-html
sbt +publish-local

sbt docker
