#!/usr/bin/env bash
set -e
set -o pipefail

export CI=true # also set by travis, but helps when running locally
export WUST_STAGE=dev

sbt -Dquill.macro.log=false docker \
 testJS \
 coverage testJVM coverageReport
