#!/usr/bin/env bash
set -e
set -o pipefail

export CI=true # also set by travis, but helps when running locally

sbt \
 -Dquill.macro.log=false \
 coverage testJVM coverageReport \
 testJSNonPure \
 compileAndroid \
 it:compile \
 docker
