#!/usr/bin/env bash
set -e
set -o pipefail

cd-tmp () {
	local t
	t=$(mktemp -d)
	echo "$t"
	builtin cd "$t"
}

# if [ -d "$HOME/.ivy2/local/com.github.fdietze/scalarx_sjs0.6_2.12/0.3.3-SNAPSHOT" ]; then
#     echo "no need to build scalarx, it already exists"
# else
# (

#     cd-tmp
#     git clone http://github.com/fdietze/scala.rx --depth=1
#     cd scala.rx
#     sbt ++2.12.3 scalarxJS/publish-local
# )
# fi

