#!/bin/bash -e

[[ "$TRAVIS_BRANCH" == "master" ]] || exit 0

docker images
#TODO
# docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
# docker push woost/wust2
# docker push woost/wust2.db-migration
# docker push woost/wust2.nginx
