#!/bin/bash -e

./start test.postgres

./start test.integration

HOST_DOMAIN=localhost POSTGRES_USER=travis POSTGRES_PASSWORD=travis ./start prod.http
nc -z localhost 80
docker stop $(docker ps -q)

HOST_DOMAIN=localhost POSTGRES_USER=travis POSTGRES_PASSWORD=travis NGINX_VOLUME=$PWD/.travis SSL_CERT=test_cert.pem SSL_KEY=test_key.pem ./start prod
nc -z localhost 443
docker stop $(docker ps -q)
