#!/usr/bin/env bash
set -e
set -o pipefail

export CI=true # also set by ci server, but helps when running locally

export SOURCEMAPS=false # for building production js assets with sourcemap

# building with sbt needs around 2G, 300M Metaspace
export _JAVA_OPTIONS="-Xms2000M -Xmx2500M -XX:MaxMetaspaceSize=350M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

sbt core/docker dbMigration/docker webApp/docker || node /root/repo/webApp/target/scala-2.12/scalajs-bundler/main/node_modules/webpack/bin/webpack --bail --profile --json --config /root/repo/webApp/target/scala-2.12/scalajs-bundler/main/webpack.config.prod.js
