#!/usr/bin/env bash
set -e
set -o pipefail

export CI=true # also set by ci server, but helps when running locally

export SOURCEMAPS=false # for building production js assets with sourcemap

# building with sbt needs around 2G, 300M Metaspace
export _JAVA_OPTIONS="-Xms2000M -Xmx2500M -XX:MaxMetaspaceSize=350M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

# We compile integration tests here, since the compiler is already hot and gives us a faster feedback

# Scalajs isssue: https://github.com/scoverage/scalac-scoverage-plugin/issues/196
# sbt \
#  -Dquill.macro.log=false \
#  compile \
#  coverage \
#  testJVM \
#  coverageReport \
#  coverageOff \
#  testJSNonPure \
#  it:compile \
#  docker

sbt \
 -Dquill.macro.log=false \
 compile \
 testJVM \
 testJSNonPure \
