#!/usr/bin/env bash
set -e
set -o pipefail

[[ -n "$DOCKER_USERNAME" ]] || exit 0
[[ -n "$DOCKER_PASSWORD" ]] || exit 0
[[ -n "$DOCKER_REGISTRY" ]] || exit 0

docker images
echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" "$DOCKER_REGISTRY" --password-stdin;

docker push "$DOCKER_REGISTRY/woost/db-migration"
docker push "$DOCKER_REGISTRY/woost/core"
docker push "$DOCKER_REGISTRY/woost/web"
# docker push "$DOCKER_REGISTRY/woost/github"
# docker push "$DOCKER_REGISTRY/woost/gitter"
docker push "$DOCKER_REGISTRY/woost/slack"

[[ "$CIRCLE_BRANCH" == "master" ]] && [[ -n "$STAGING_URL" ]] || exit 0
echo "Triggering deploy..."
curl "$STAGING_URL" 2> /dev/null
