#!/usr/bin/env bash
set -e
set -o pipefail

# building with sbt needs around 3G
export _JAVA_OPTIONS="-Xms128M -Xmx2800M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

./start test.integration
