#!/usr/bin/env bash
set -e
set -o pipefail

# building with sbt needs around 2G, 300M Metaspace
export _JAVA_OPTIONS="-Xms2000M -Xmx2850M -XX:MetaspaceSize=300M -XX:MaxMetaspaceSize=350M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

./start test.integration
