// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "org.scala-lang.modules" % "scala-java8-compat_2.11" % "0.7.0",
  "org.scalaz" % "scalaz-core_2.11" % "7.3.0-M13"
)
// LIBRARY_DEPENDENCIES_HASH 73fb68ae6345d5653a73701882e4ccae0d15710b
