// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.lihaoyi" % "scalatags_sjs0.6_2.11" % "0.6.5",
  "com.lihaoyi" % "sourcecode_sjs0.6_2.11" % "0.1.3",
  "io.suzaku" % "boopickle_sjs0.6_2.11" % "1.2.6",
  "org.scala-js" % "scalajs-dom_sjs0.6_2.11" % "0.9.1",
  "org.scala-js" % "scalajs-java-time_sjs0.6_2.11" % "0.2.1",
  "org.scala-js" % "scalajs-library_2.11" % "0.6.16",
  "org.scalaz" % "scalaz-core_sjs0.6_2.11" % "7.3.0-M13"
)
// LIBRARY_DEPENDENCIES_HASH 35f34d95d2992501bb30894a403895d0291ff005
